Initial task
HurricaneSKC/movie-app pull request #1
Opened 2021-06-01 09:54 UTC by HurricaneSKC

2021-06-03 16:52 UTC, elkinny requested changes
- Don't keeps types separately from component. It's usually more convenient to keep them in the component folder so you always know where to look at

2021-06-03 16:52 UTC, elkinny commented on src/components/Modal/Modal.tsx
> +        <React.Fragment>
```suggestion
        <>
```
There is a syntax sugar for fragment. same thing, just looks better)

2021-06-03 16:52 UTC, elkinny commented on src/components/Modal/Modal.tsx
> +            aria-hidden
I think that attribute should depend on isShowing prop

2021-06-03 16:52 UTC, elkinny commented on src/components/Modal/Modal.tsx
> +            tabIndex={-1}
I believe this one is redundant as divs are not reachable with tab in the first place

2021-06-03 16:52 UTC, elkinny commented on src/components/MoviesContainer/GenreList/GenreList.tsx
> +let genreArray: string[] = [];
whould recommend to mark it with comment like
`//TODO: Remove when integrated with real API`

Later it'll probably be moved out completely or moved in actions of Redux

2021-06-03 16:52 UTC, elkinny commented on src/components/MoviesContainer/GenreList/GenreList.tsx
> +      <GenreListItem key={index} genre={genre} />
don't use indexes as keys. In case order of events change or you delete data from array, it may cause redundant re-renderings and errors. Something that will stay with your item forever, like genre name itself

2021-06-03 16:52 UTC, elkinny commented on src/components/MoviesContainer/MovieSearchContainer/MovieSearch.tsx
> +      filterOnChange={() => console.log("changed")}
I understand that it's just placeholder for now, but a small note for future
Avoid putting arrow functions in callbacks. I'll cause redundant re-render of the child when parent serenaders (as you pass new function from parent to child); if you can (if it is pure function of can become one), put callback function outside of the functional component. If you can't, use useCallback

2021-06-03 16:52 UTC, elkinny commented on src/components/MoviesContainer/MovieList/MovieList.tsx
> +    {movies.data.map((movie) => (
```suggestion
    {movies.data.map(({id, title, release_date, poster_path, genres}) => (
```

Just to make code cleaner and get rid of repetitive movie.something

2021-06-03 21:00 UTC, HurricaneSKC commented on src/components/Modal/Modal.tsx
> +            aria-hidden
I am not too sure about this one as the whole div is depended on the isShowing prop

2021-06-04 08:16 UTC, HurricaneSKC commented
> * Don't keeps types separately from component. It's usually more convenient to keep them in the component folder so you always know where to look at

I am not too sure what you mean here - would you be able to provide an example - thanks :)

2021-06-10 09:35 UTC, merged